### ISSUE TITLE
控制台输出会影响写代码。。。

### ISSUE THREAD

**Issue by hahajie147** [chengyoujie/egretautocodeeui#1]
每次Ctrl+S的时候 鼠标光标都会跳到控制台的输出面板上。。影响码代码。

**Comment by chengyoujie** [comment]
> 每次Ctrl+S的时候 鼠标光标都会跳到控制台的输出面板上。。影响码代码。

这边测试没有发现这种现象，插件没有对ctrl+s处理，换下其他机器看下会不会有同样的问题。如果有同样的问题可以录下视频发至1137815160@qq.com

**Comment by chengyoujie** [comment]
新版本已修复
